// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvBzcXs5Hy0lCjGbPx-JYzhchHe6BeYM',
    appId: '1:1054396414952:android:989f37db77622c7748c25d',
    messagingSenderId: '1054396414952',
    projectId: 'novus-guard-solo-341004',
    storageBucket: 'novus-guard-solo-341004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1ypMj60Nrwl12cZLNuZCEPq7t4tdwxQ',
    appId: '1:1054396414952:ios:022f4cae043a8df148c25d',
    messagingSenderId: '1054396414952',
    projectId: 'novus-guard-solo-341004',
    storageBucket: 'novus-guard-solo-341004.appspot.com',
    iosClientId: '1054396414952-i50hmuvr7qjvuehsvdhdtn0g5249b4ml.apps.googleusercontent.com',
    iosBundleId: 'com.novusguardsolo',
  );
}
